# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a2aaf2ca7b4c339a7a082adfe75f87d6820f192c176392597ccfa22982eae9554dbee39a934b64ce7111ec732015a8c36f99fa57df460598c2bcee1e3598241

test:
  secret_key_base: f0f427532f9a916f75d8f873481a49a84d728d3e46f9908c3150bf174916bd2047eac93c4edca39d38372a3a69d00b67fee8bc149867ab2b218eb3038bba7011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
